# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/iso" = {
    device = "/dev/disk/by-uuid/1980-01-01-00-00-00-00";
    fsType = "iso9660";
  };

  fileSystems."/nix/.ro-store" = {
    device = "/iso/nix-store.squashfs";
    fsType = "squashfs";
    options = ["loop"];
  };

  fileSystems."/nix/.rw-store" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/nix/store" = {
    device = "overlay";
    fsType = "overlay";
  };

  fileSystems."/mnt" = {
    device = "/dev/disk/by-uuid/8ffe6c0b-1aad-4ba0-95e7-299f4dce0cda";
    fsType = "ext4";
  };

  fileSystems."/mnt/boot" = {
    device = "/dev/disk/by-uuid/944c8fc6-0092-4b74-b594-3d9973cb23e0";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/be5315d0-a6d8-47d2-a4fa-8ce4f2db4535";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
