# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8ffe6c0b-1aad-4ba0-95e7-299f4dce0cda";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/944c8fc6-0092-4b74-b594-3d9973cb23e0";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/be5315d0-a6d8-47d2-a4fa-8ce4f2db4535";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
