# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-4c59e2e8-4b2b-472b-9231-8c9d8c8ac2d1";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4c59e2e8-4b2b-472b-9231-8c9d8c8ac2d1".device = "/dev/disk/by-uuid/4c59e2e8-4b2b-472b-9231-8c9d8c8ac2d1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/830A-C3FA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
